name = "nezumi"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

[[kv_namespaces]]
binding = "KV"
id = "3fc909d549ba4cecb3b25bfcb4054c33"

[[d1_databases]]
binding = "DB"
database_name = "nezumi-db"
database_id = "4839b0a3-2d94-46aa-9a37-ee545297bb1b"

[assets]
directory = "./client/dist"
binding = "ASSETS"

[triggers]
crons = ["*/15 * * * *"]
