name = "nezumi"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

[[kv_namespaces]]
binding = "KV"
id = "79dfd28044184ddab4f67b34a2b788b1"

[[d1_databases]]
binding = "DB"
database_name = "nezumi-db"
database_id = "REPLACE_WITH_D1_ID"

[assets]
directory = "./client/dist"
binding = "ASSETS"

[triggers]
crons = ["*/15 * * * *"]
